# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/simple.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/simple.proto\"\x14\n\x06Simple\x12\n\n\x02id\x18\x01 \x01(\rb\x06proto3')



_SIMPLE = DESCRIPTOR.message_types_by_name['Simple']
Simple = _reflection.GeneratedProtocolMessageType('Simple', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLE,
  '__module__' : 'proto.simple_pb2'
  # @@protoc_insertion_point(class_scope:Simple)
  })
_sym_db.RegisterMessage(Simple)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMPLE._serialized_start=22
  _SIMPLE._serialized_end=42
# @@protoc_insertion_point(module_scope)
